### ISSUE TITLE
Does not produce a flatpak file

### ISSUE THREAD

**Issue by sramkrishna** [vrutkovs/flatpak-tilix#1]
Perhaps I'm doing it incorrectly, but I'm not sure what happens after I type make. I do not see a flatpak of the tilix in this case?

**Comment by sramkrishna** [comment]
Never mind.  :-)  it dosen't quite work as it doesn't load bash.  But I'll file that elsewhere.

**Comment by vrutkovs** [comment]
It should create a repo in `repo` folder, which would later on be added via `flatpak --user remote-add --if-not-exists --no-gpg-verify local-tilix repo` and install Tilix via `flatpak install --user local-tilix com.gexperts.Tilix`
